### ISSUE TITLE
What falls into the category of "other tensors"?

### ISSUE THREAD

**Issue by l-oneil** [oxmlsys/tflite-tools#3]
Hi, 

Thanks for this tool - looks to work great! 

Just looking at the output graphs, I see a substantial amount of my data is falling into the category of "other tensors", what exactly does all this additional data consist of? 

Best Regards, 
Liam

**Comment by eliberis** [comment]
Hey,

That's tensors held behind for subsequent operators (i.e. not the input or
the output of the operator currently being executed) --- happens when you
have branches / residual connections in your architecture.
Also, a small note: it doesn't currently show any "scratch space" than an
operator might allocate for itself at runtime (the amount depends on the
implementation).

Best,
Edgar

**Comment by l-oneil** [comment]
Thanks for clarifying and the prompt response! :)
